### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by torch2424** [Malax/elmboy#1]
Hello!

Just wanted to reach out, I also make GB emulators, I've been working [wasmBoy](https://github.com/torch2424/wasmBoy) for a while now. 

I just wanted to mention there's a really good GB communitty at [awesome-gbdev](https://github.com/gbdev/awesome-gbdev). We have a discord, and chat a lot about internals and other random GB stuff. I don't lurk there as often as I should, but definitely a great resource and awesome people to chat with.

Also, if you need any help with things like implementing Sound, or GBC. Feel free to reach out, glad to answer any questions. I've played with elm a tiny bit, but nothing on this scale haha!

Have a nice day! 😄

**Comment by Malax** [comment]
Hey @torch2424!

Thanks for reaching out, I'll definitely join the discord! It's always nice to talk to like-minded developers! I probably have a lot of questions in the future that go beyond the pandoc when this thing gets more accurate. As of now, I'm trying to get performance up to 60 FPS before I tackle new features. :) 

Again, thank you! 👍
