### ISSUE TITLE
Pass Blargg's Test Roms

### ISSUE THREAD

**Issue by Malax** [Malax/elmboy#2]
- [x] 01-special.gb
- [x] 02-interrupts.gb
- [x] 03-op sp,hl.gb
- [x] 04-op r,imm.gb
- [x] 05-op rp.gb
- [x] 06-ld r,r.gb
- [x] 07-jr,jp,call,ret,rst.gb
- [x] 08-misc instrs.gb
- [x] 09-op r,r.gb
- [x] 10-bit ops.gb
- [x] 11-op a,(hl).gb

**Comment by Malax** [comment]
After some digging, I found the reason why `02-interrupts.gb` does not terminate. It locks up in a state where the CPU is halted, IME is off and a timer interrupt occurs. This guy has the same problem in his emulator: https://www.reddit.com/r/EmuDev/comments/5ie3k7/infinite_loop_trying_to_pass_blarggs_interrupt/

**Comment by Malax** [comment]
![grafik](https://user-images.githubusercontent.com/177877/49734371-5a8ef100-fc84-11e8-8359-81765fdcf5a0.png)

**Comment by d4ilyrun** [comment]
Congrats! 🎉
